{% set python_min = '3.12' %}
{% set name = "spoc" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spoc-{{ version }}.tar.gz
  sha256: 17c31dfd9925b4836ebd074ea1417b4c589bdefbe665215be90b49da7138e5b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - spoc-init=spoc:start_project

requirements:
  host:
    - pip
    - pdm-backend
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - spoc
  commands:
    - pip check
    - spoc-init -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hlop3z/spoc
  doc_url: https://hlop3z.github.io/spoc/
  summary: Elastic framework builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
