{% set name = "spoc" %}
{% set version = "0.1.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spoc-{{ version }}.tar.gz
  sha256: b70e489545d866367898571f985445a255a33e2f2976ea491bd645849171b58f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - spoc-init=spoc:start_project

requirements:
  host:
    - pip
    - pdm-pep517 >=1.0.0
    - python >=3.12
  run:
    - python >=3.12

test:
  imports:
    - spoc
  commands:
    - pip check
    - spoc-init -h
  requires:
    - pip

about:
  home: https://github.com/hlop3z/spoc
  doc_url: https://hlop3z.github.io/spoc/
  summary: Elastic framework builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
