{% set name = "spoc" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spoc-{{ version }}.tar.gz
  sha256: 3fcd36cd9dc1e94670995756c23da4c9d1060364232017af0ac827b475b34e67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - spoc-init=spoc:start_project

requirements:
  host:
    - pip
    - hatchling
    - python >=3.12
  run:
    - python >=3.12

test:
  imports:
    - spoc
  commands:
    - pip check
    - spoc-init -h
  requires:
    - pip

about:
  home: https://github.com/hlop3z/spoc
  doc_url: https://hlop3z.github.io/spoc/
  summary: Elastic framework builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
