{% set name = "spoc" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spoc-{{ version }}.tar.gz
  sha256: ac153296752655f3915573d8de66fa4e0dc4d2d1237fa49661b37ae5575755e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pdm-pep517 >=1.0.0
    - python >=3.10
  run:
    - python >=3.10
    - toml >=0.10.2

test:
  source_files:
    - tests
  commands:
    - pip check
    - cd tests
    - python main.py
  requires:
    - pip
    - pytest

about:
  home: https://github.com/hlop3z/spoc
  doc_url: https://hlop3z.github.io/spoc/
  summary: Elastic framework builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
