{% set python_min = "3.12" %}
{% set name = "spoc" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spoc-{{ version }}.tar.gz
  sha256: 636c15cdd7b2fde2286069ee1bac6d38220049994c4f6c0696c550b3e628849e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - spoc-init=spoc:start_project

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - spoc
  commands:
    - pip check
    - spoc-init -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hlop3z/spoc
  doc_url: https://hlop3z.github.io/spoc/
  summary: Elastic framework builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
