schema_version: 1

context:
  python_min: "3.13"
  name: spoc
  version: "0.3.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/spoc-${{ version }}.tar.gz
  sha256: 9d543903d5fa697262a1cb599b39cd32eb2423626bb0ab21ee31ca9fed40e522

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - spoc
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Elastic framework builder
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/hlop3z/spoc
  documentation: https://hlop3z.github.io/spoc/

extra:
  recipe-maintainers:
    - thewchan
